# Without nginx
services:
  mongodb:
    image: mongo
    volumes:
      - mongodbdata:/data/db
    env_file:
      - ./env/mongo.env
    container_name: mongodb
  backend: 
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    volumes: 
      - ./nodejs:/nodejs
    ports:
      - 5000:5000
    env_file:
      - ./env/nodejs.env
    depends_on:
      - mongodb
    container_name: backend
  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile.dev
    volumes:
      - ./react/src:/react/src
    ports:
      - 3000:3000
    depends_on:
      - backend
    stdin_open: true
    tty: true
    container_name: frontend

volumes: 
  mongodbdata:


# # With nginx
# services:
#   mongodb:
#     image: mongo
#     volumes:
#       - mongodbdata:/data/db
#     env_file:
#       - ./env/mongo.env
#     container_name: mongodb
#   backend: 
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     volumes: 
#       - ./backend/src:/app/src
#     ports:
#       - 8000:5000
#     env_file:
#       - ./env/backend.env
#     depends_on:
#       - mongodb
#     container_name: backend
#   frontend:
#     build: 
#       context: ./frontend
#       dockerfile: Dockerfile
#     ports:
#       - 80:80
#     depends_on:
#       - backend
#     stdin_open: false
#     tty: false

# volumes: 
#   mongodbdata:




