export const GET_POSTS_BEGIN = 'GET_POSTS_BEGIN'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'

export const GET_FOLLOWING_POSTS_BEGIN = 'GET_FOLLOWING_POSTS_BEGIN'
export const GET_FOLLOWING_POSTS_SUCCESS = 'GET_FOLLOWING_POSTS_SUCCESS'

export const LOAD_MORE_POSTS_SUCCESS = 'LOAD_MORE_POSTS_SUCCESS'

export const LOAD_MORE_PROFILE_POSTS_SUCCESS = 'LOAD_MORE_PROFILE_POSTS_SUCCESS'

export const GET_PROFILE_POSTS_BEGIN = 'GET_PROFILE_POSTS_BEGIN'
export const GET_PROFILE_POSTS_SUCCESS = 'GET_PROFILE_POSTS_SUCCESS'

export const ADD_POST_BEGIN = 'ADD_POST_BEGIN'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'

export const SHOW_PROFILE = 'SHOW_PROFILE'

export const GET_USER_BEGIN = 'GET_USER_BEGIN'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const UPDATE_AVATAR_SUCCESS = "UPDATE_AVATAR_SUCCESS"

export const LOGOUT_USER = 'LOGOUT_USER'

export const GET_POST_COMMENTS_SUCCESS = 'GET_POST_COMMENTS_SUCCESS'

export const SUBMIT_COMMENT_ERROR = 'SUBMIT_COMMENT_ERROR'

export const CLEAR_STATES = 'CLEAR_STATES'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const TOGGLE_UPLOAD_MODAL = 'TOGGLE_UPLOAD_MODAL'

export const TOGGLE_POST_MODAL = 'TOGGLE_POST_MODAL'

export const TOGGLE_OPTION_MODAL = 'TOGGLE_OPTION_MODAL'
export const HIDE_OPTION_MODAL = 'HIDE_OPTION_MODAL'

export const TOGGLE_EDIT_MODAL = 'TOGGLE_EDIT_MODAL'
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS"

export const SHOW_DROPDOWN = 'SHOW_DROPDOWN'

export const GET_FOLLOW_CONDITION_SUCCESS = 'GET_FOLLOW_CONDITION_SUCCESS'

export const CHANGE_FOLLOW_CONDITION_SUCCESS = 'CHANGE_FOLLOW_CONDITION_SUCCESS'
